import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { getSession } from '@auth0/nextjs-auth0';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const user = session ? session.user : null;

  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <nav className="navbar">
            <ul className="navbar-list">
              <li className="navbar-item"><a href="/">Home</a></li>
              {user !== null ? (
                <>
                  <li className="navbar-item"><a href="/users/me">Profile</a></li>
                  <li className="navbar-item"><a href="/api/auth/logout">Logout</a></li>
                  <li className="navbar-item user-info">
                    <div className="user-profile">
                      <img src={user.picture} alt={user.name} className="user-image" />
                      <p className="user-name">Hi {user.name}</p>
                    </div>
                  </li>
                </>
              ) : (
                <li className="navbar-item"><a href="/api/auth/login">Login To Play!</a></li>
              )}
            </ul>
          </nav>
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
